global using FluentValidation;
global using MASA.BuildingBlocks.Data.Uow;
global using MASA.BuildingBlocks.Dispatcher.InMemory;
global using MASA.EShop.Services.Catalog.Application.CatalogTypes;
global using MASA.EShop.Services.Catalog.Application.CatalogTypes.Commands;
global using MASA.EShop.Services.Catalog.Domain.Entities;
global using MASA.EShop.Services.Catalog.Domain.Repositories.Interfaces;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Moq;
