global using Dapr;
global using Dapr.Client;
global using MASA.BuildingBlocks.Dispatcher.IntegrationEvents;
global using MASA.BuildingBlocks.Dispatcher.IntegrationEvents.Logs;
global using MASA.Contrib.Dispatcher.IntegrationEvents.Dapr;
global using MASA.Contrib.Dispatcher.IntegrationEvents.EventLogs.EF;
global using MASA.Contrib.Service.MinimalAPIs;
global using MASA.EShop.Contracts.Basket;
global using MASA.EShop.Contracts.Basket.Model;
global using MASA.EShop.Services.Basket.Infrastructure.Repositories;
global using MASA.EShop.Services.Basket.Model;
global using MASA.Utils.Data.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.OpenApi.Models;
global using System.ComponentModel.DataAnnotations;
global using System.Reflection;

